#!/usr/bin/php
<?php


//define('DIR', '/home/cupivan/http/_.cupivan.ru/osm/validator/parser/');
//define('DIR', "D:\\kool\\validator\\parser\\");
$DIR = "D:\\kool\\validator\\common";

if ($_SERVER['argc'] < 2)
{
	echo "Usage: osm_test_validator VALIDATOR REGION [options]\n".
		 "Options:\n".
		 "  --all - show all objects\n".
		 "Example: osm_test_validator sberbank RU-MOS\n";
	exit;
}

$validator = @$_SERVER['argv'][1];
$region    = @$_SERVER['argv'][2];

// дополнительные параметры
$params = implode(',', $_SERVER['argv']);
if (strpos($params, '--all')) define('SHOW_ALL', 1);

//echo  "----------\n";
//echo $_SERVER["DOCUMENT_ROOT"]."\n";


//chdir($DIR . 'common\\');
chdir($DIR);

//if (!$fname = exec("find ".$DIR." -name $validator.php"))
//{
//	echo "Unknow validator '$validator'\n";
//	exit;
//}
//else


//надо найти фаел с таким именем...
$searchfile = $DIR."\\..\\parser\\*\\$validator.php";
$files = glob($searchfile);
if (!$files)
{
    echo "Unknown validator ".$validator;
    return;
}
//Код валидатора, например parser\bank\alfabank.php
require_once $files[0];

//	require_once $fname;


try
{
	$v = new $validator($region);
	$v->useCacheHtml = 1;
	$v->update();
	$list = $v->getObjects();
	echo "Total objects: ".count($list)."\n";
	echo "First object:\n";
	if (defined('SHOW_ALL'))
		print_r($list);
	else
		print_r(@$list[0]);
}
catch(Exception $e)
{
	echo 'Error: '.$e->getMessage()."\n";
	exit;
}
